additional_cargo_args = ["--all-features"]
cap_lints = true
exclude_re = [
    # "disabled" is default value
    "src/scheduler.rs:260:9: replace GarbageCollector::disabled -> Self with Default::default()",
]
