name: Continuous integration
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 5"

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - 1.82

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        name: Setup toolchain
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt,clippy

      - name: Build
        run: cargo build

      - name: Test
        env:
          CI: true
        run: cargo test --all-features

      - name: Fmt
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all --all-features -- -D warnings

      - name: Install cargo-hack
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack

      - name: Check feature-powerset
        run: cargo hack check --no-dev-deps --feature-powerset

      - name: Check each-feature
        run: cargo hack check --no-dev-deps --each-feature

      - name: Tests feature-powerset
        run: cargo hack test --feature-powerset

      - name: Tests each-feature
        run: cargo hack test --each-feature

  semver-checks:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
