name: Continuous integration
on:
  pull_request:
  schedule:
    - cron: "0 9 * * 5"

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - 1.75.0
        features:
          - ""
          - async-trait

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        name: Setup toolchain
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt,clippy

      - name: Build
        run: cargo build -F "${{ matrix.features }}"

      - name: Test
        env:
          CI: true
        run: cargo test -F "${{ matrix.features }}"

      - name: Fmt
        run: cargo fmt --all -- --check

      - name: Clippy
        run: |
          cargo clippy -F "${{ matrix.features }}" -- -D warnings
          cargo clippy --tests -F "${{ matrix.features }}" -- -D warnings

  codecov:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v4

      - name: Setup for testing
        run: |
          rustup toolchain add nightly --component llvm-tools-preview
          rustup override set nightly

      - name: Test with coverage
        env:
          CI: true
          RUSTFLAGS: -Cinstrument-coverage
          LLVM_PROFILE_FILE: grcov-%p-%m.profraw
        run: cargo test -F "${{ matrix.features }}"

      - name: Generate coverage
        run: |
          ./target/debug/grcov $(find . -name "grcov-*.profraw" -print) \
            --branch \
            --ignore-not-existing \
            --binary-path ./target/debug/ \
            -s . \
            -t lcov \
            --ignore "/*" \
            -o lcov.info

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
